### ISSUE TITLE
TypeError: expected string  [draw.textsize(font)]

### ISSUE THREAD

**Issue by SysoevDV** [python-pillow/Pillow#2117]
### That piece of code:
```python
W, H = (1285,720)
text = "Hello world"
img = Image.open("img.png")
draw = ImageDraw.Draw(img)
font = ImageFont.truetype("/usr/share/fonts/MyriadProCondBold.ttf", 90)
w, h = draw.textsize(text.encode('utf-8'), font=font)
draw.text(((W-w)/2,520),text,(255,255,255),font=font)
```
### Output:
```python
w, h = draw.textsize(text.encode('utf-8'), font=font)
  File "/usr/lib/python3.5/site-packages/PIL/ImageDraw.py", line 273, in textsize
    return font.getsize(text)
  File "/usr/lib/python3.5/site-packages/PIL/ImageFont.py", line 141, in getsize
    size, offset = self.font.getsize(text)
TypeError: expected string
```

**Comment by radarhere** [comment]
Just as an explanation of what's happening - you are passing in bytes when it 'expected string'. If you change `text.encode('utf-8')` to just `text`, you should find that the code runs without a problem.

**Comment by radarhere** [comment]
Thanks for the thumbs up response. If you feel like that resolves your situation, please close this issue.

**Comment by SysoevDV** [comment]
@radarhere **thanks for the help. You've been very much helped me. Issue has been resolved!**

**Comment by caozhen-zen** [comment]
> Just as an explanation of what's happening - you are passing in bytes when it 'expected string'. If you change `text.encode('utf-8')` to just `text`, you should find that the code runs without a problem.

Hi radarhere,

Thank you very much for your reply. I also have this problem. While this method doesn't solve it since I need to print Japanese string like `道の駅`, if I remove `.encode('utf-8')`,  `UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-2: ordinal not in range(256)` will be prompt. It's in a dilemma. Could you advise? 

Thank you.

**Comment by nulano** [comment]
@caozhen-zen Are you using the default (PIL) font? TrueType fonts don't convert the input to Latin-1. Could you open a new issue stating the font you are using, your Operating System and Python version?
