### ISSUE TITLE
How to render stacked Tibetan letters

### ISSUE THREAD

**Issue by serser** [python-pillow/Pillow#2572]
Hello Pillow folks, I've come across this issue with stacked texts in Tibetan (po-ed stackoverflow question [here)](https://stackoverflow.com/questions/44394027/problems-writing-tibetan-stacked-texts-with-imagedraw).

```python
from PIL import Image, ImageFont, ImageDraw
import matplotlib.pyplot as plt

test_letters = [u'ཀ', u'ར',u"སྤ",u'རྐ',u'༄',u'ཀྱ',u'ཛྷ']

font = ImageFont.truetype("/Libarary/Fonts/Kokonor.ttf", 20, encoding='unic')

for letter in test_letters:
    img = Image.new("RGBA", (28, 28))
    draw = ImageDraw.Draw(img)
    draw.text((6, 0),letter,(0,0,0),font)
    plt.imshow(img)
    plt.grid()
    plt.show()
```
One of the output is like this one, displayed apart.
![image](https://user-images.githubusercontent.com/3620404/26985103-a00fd1ec-4d74-11e7-8748-5b1fc9f99ebb.png).

There are some links on Tibetan font rendering, which might of some value. 
1. https://www.microsoft.com/typography/OpenTypeDev/tibetan/intro.htm
2. http://digitaltibetan.org/index.php/Formatting_rules_for_Tibetan_text
3. https://collab.its.virginia.edu/wiki/tibetan-script/Using%20Tibetan%20in%20Macintoshes.html

Thanks for any illumination.

**Comment by wiredfool** [comment]
I suspect it's the same underlying issue that's fixed in #2284.

**Comment by serser** [comment]
Thanks for rapid reply wired, I see that is still on a branch to be merged to master due to conflicts. I will give a try.

**Comment by serser** [comment]
@wiredfool with `libraqm` compiled and installed, and pip installed `Fahad-Alsaidi/Pillow@CTL` branch, do I need to alter anything to solve this issue? It seems that the letters still don't stack.

**Comment by wiredfool** [comment]
If that's the case, then there are 3 possibilities:

- The CTL branch didn't actually compile correctly and the feature isn't available. One issue with that PR is that the feature reporting is incorrect. I've got a fix, and another PR that it relied on is merged, so it's time to get back to that and push it off my machine. It's possible that you have raqm installed, but Pillow couldn't find harfbuzz or fribdi.
- The CTL branch is supposed to handle this case, and doesn't do it correctly.
- It's a separate issue. From a quick google, it does appear that harfbuzz is supposed to to Tibetan script, so I'm going to count this as unlikely.

**Comment by wiredfool** [comment]
So, I've got a branch where I'm testing out the complex text layout PR (#2576) and using the following script, I've got something that appears to match what I'm seeing in the editor and libreoffice on Ubuntu 16.04. This is using the font package 'fonts-tibetan-machine', and displaying the whole thing as one string rather than individual glyphs in matplotlib.

![issue_2572](https://user-images.githubusercontent.com/19792/27104395-0c5e12a2-5084-11e7-8058-fb96d88eda06.png)

```#!/usr/bin/env python
# -*- coding: utf-8 -*-

from PIL import Image, ImageFont, ImageDraw

test_str = u'ཀ ར སྤ རྐ ༄ ཀྱ ཛྷ'

font = ImageFont.truetype("TibetanMachineUni.ttf", 40, encoding='unic')

img = Image.new("RGBA", (320, 60), 'white')
draw = ImageDraw.Draw(img)
draw.text((6, 0),test_str,(0,0,0),font)
img.save('issue_2572.png')
```

To my eye, it looks correct, but I'm not an expert by any means.

**Comment by hugovk** [comment]
I get this on master (Python 2.7.13, macOS, with no RAQM pre-requisites):

![image](https://user-images.githubusercontent.com/1324225/27119892-4c092980-50ea-11e7-8e0f-856a84097569.png)

And this on wiredfool/pr_2284:

![image](https://user-images.githubusercontent.com/1324225/27120084-efa9dd5a-50ea-11e7-9a07-b1657089ca25.png)

**Comment by wiredfool** [comment]
Is the top one a cropping issue, or is it a rendering thing?

**Comment by hugovk** [comment]
Looks like rendering. With 640px width:

![image](https://user-images.githubusercontent.com/1324225/27123630-26ab8716-50f7-11e7-9ede-3497ff7bd4f6.png)

**Comment by wiredfool** [comment]
That's odd. Wonder if it's a freetype version issue, or if it's a font thing. It looks like you have the same font, so that's not likely to be it.

**Comment by hugovk** [comment]
I used this font: https://github.com/cscott/mw-ocg-latexer/blob/master/fonts/tibetan-machine/TibetanMachineUni.ttf

**Comment by wiredfool** [comment]
Freetype version?

**Comment by hugovk** [comment]
Freetype 2.7.1: `/usr/local/Cellar/freetype/2.7.1`

**Comment by wiredfool** [comment]
12.04:
```
(vpy27)erics@builder-1204-x64:~/Pillow$ dpkg -l | grep -i freetype
ii  libfreetype6                         2.4.8-1ubuntu2.4                    FreeType 2 font engine, shared library files
```

16.04:
```
(vpy27) erics@builder-16:~/Pillow$ dpkg -l | grep freetype
ii  libfreetype6:amd64                2.6.1-0.1ubuntu2.3                         amd64        FreeType 2 font engine, shared library files
```

Hmm.

**Comment by serser** [comment]
Thanks @hugovk  and @wiredfool  It seems that fonts are handled with some preference.  To notice although some of them are stacked, they are not rendered properly. `Kokonor` and `Kailasa` are default on macOS, and rendered all right when typed as texts.

![image](https://user-images.githubusercontent.com/3620404/27143554-50483bb8-5161-11e7-9e86-b811351d6d52.png)

**Comment by wiredfool** [comment]
I've checked this with the mac fonts on an Ubuntu 16.04 machine, and it's the font, not the freetype version. So there's something different in the fonts.

**Comment by wiredfool** [comment]
@Fahad-Alsaidi Can you take a look at this and see if raqm + harfbuzz is properly parsing this as Tibetan and enabling the appropriate script options? If not, is there a way to override any detected script and pass in Tibetan, either as a feature or otherwise?  (i.e., I'm seeing 'TIB ' and 'Tibt' in the harfbuzz source, but neither seem to affect the rendering)

**Comment by Fahad-Alsaidi** [comment]
well, have you tried this [raqm_set_language ()](http://host-oman.github.io/libraqm/raqm-Raqm.html#raqm-set-language).  I think this isn't implement yet in the original PR.

**Comment by khaledhosny** [comment]
Mac system fonts are likely to be AAT not OpenType fonts, so they will not work on Windows or Linux correctly. On Mac AAT fonts should work if HarfBuzz is compiled with Core Text support.

**Comment by weirman** [comment]
Hello Pillow folks,I read the response to this question, but I still don't know how to solve the problem.
I use `/usr/share/fonts/truetype/tibetan-machine/TibetanMachineUni.ttf` On 64-bit Ubuntu 16.04，to test the following code.
```python 
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from PIL import Image, ImageFont, ImageDraw
test_str = u'ཀ ར སྤ རྐ ༄ ཀྱ ཛྷ'
font = ImageFont.truetype("TibetanMachineUni.ttf", 40, encoding='unic')
img = Image.new("RGBA", (320, 60), 'white')
draw = ImageDraw.Draw(img)
draw.text((6, 0),test_str,(0,0,0),font)
img.save('issue_2572.png')
```
But here's what I get.

![image](https://user-images.githubusercontent.com/1324225/27120084-efa9dd5a-50ea-11e7-9a07-b1657089ca25.png)

Freetype version:
```bash 
libfreetype6:amd64                         2.6.1-0.1ubuntu2.3                                  amd64        FreeType 2 font engine, shared library files
libfreetype6-dev:amd64                     2.6.1-0.1ubuntu2.3                                  amd64        FreeType 2 font engine, development files
```

The libs I installed is shown below:
```bash
weirman@ubuntu:/usr/local/lib$ ls
libfribidi.la  libfribidi.so.0      libharfbuzz.la  libharfbuzz.so.0        libraqm.so  python2.7
libfribidi.so  libfribidi.so.0.3.6  libharfbuzz.so  libharfbuzz.so.0.910.0  pkgconfig   python3.5

weirman@ubuntu:/usr/local/bin$ ls
fribidi  hb-ot-shape-closure  hb-shape
```

I don't know how the problem arose.
I want to get the same result as wiredfool.
![image](https://user-images.githubusercontent.com/19792/27104395-0c5e12a2-5084-11e7-8058-fb96d88eda06.png)

Thanks for any illumination.

**Comment by radarhere** [comment]
`raqm_set_language` was added in Pillow 6.0.0 - https://pillow.readthedocs.io/en/stable/releasenotes/6.0.0.html#new-language-parameter

**Comment by Attempt-Q** [comment]
Has the problem been solved, can anyone help me?

**Comment by ssocean** [comment]
> Has the problem been solved, can anyone help me?

try pyvip on linux

**Comment by radarhere** [comment]
#2576 was merged, which included #2284. Testing with a font downloaded from the web, the raqm support added there resolves this.

Current Pillow without raqm.
![out_0](https://user-images.githubusercontent.com/3112309/153508506-a87778a0-5d09-47af-b80a-106bed845fa4.png)
![out_1](https://user-images.githubusercontent.com/3112309/153508511-73ca7a77-7d02-4be3-8aff-49103704de91.png)
![out_2](https://user-images.githubusercontent.com/3112309/153508513-da725a32-cf0f-496d-b103-04cefeff8578.png)
![out_3](https://user-images.githubusercontent.com/3112309/153508516-f9d6fe6b-2b9e-4bb1-8558-34607aa03da4.png)
![out_4](https://user-images.githubusercontent.com/3112309/153508520-5799c5b5-f238-4f72-bcec-6aab75a7162b.png)
![out_5](https://user-images.githubusercontent.com/3112309/153508522-1d60ad39-79c7-4617-b535-03b558149c45.png)
![out_6](https://user-images.githubusercontent.com/3112309/153508525-7edc16c8-4bdd-4911-9387-f0c4099be472.png)

Current Pillow with raqm.
![out_0](https://user-images.githubusercontent.com/3112309/153508435-ad37c2d7-3a50-44ac-befe-b2e57e6f7995.png)
![out_1](https://user-images.githubusercontent.com/3112309/153508441-8f8210a9-c90b-4320-a8f6-99977666d060.png)
![out_2](https://user-images.githubusercontent.com/3112309/153508444-4f3741d5-c3d8-474d-b5ef-13cb7eb69838.png)
![out_3](https://user-images.githubusercontent.com/3112309/153508447-3cb20d07-9a0f-4f2f-9c4c-460629e13646.png)
![out_4](https://user-images.githubusercontent.com/3112309/153508448-4fc7b597-0e34-49c9-adf8-fc886d80e556.png)
![out_5](https://user-images.githubusercontent.com/3112309/153508450-389a64ab-b671-4350-b3eb-49259c168904.png)
![out_6](https://user-images.githubusercontent.com/3112309/153508451-5fc38b38-334b-42a0-904e-47d39d0752e6.png)
