### ISSUE TITLE
"ResourceWarning: unclosed file" from image.convert

### ISSUE THREAD

**Issue by mdickinson** [python-pillow/Pillow#2991]
### What did you do?

I executed a simple script (pasted below) that uses `Image.open` to open a BMP image then uses `my_image.convert("L")` to convert to a grayscale image. I regret that I can't share the image in question, but it's a 512x512 image in BMP format that contains only pure gray colors from `(0, 0, 0)` to `(255, 255, 255)`.

```
(res3)bash-4.4$ file ~/Desktop/myimage.bmp 
/Users/mdickinson/Desktop/myimage.bmp: PC bitmap, Windows 3.x format, 512 x 512 x 32
```

Here's the script:
```python
import os

from PIL import Image
import numpy as np

image_path = os.path.expanduser("~/Desktop/myimage.bmp")
image = Image.open(image_path)
new_image = image.convert("L")  # ResourceWarning here!
image_data = np.array(new_image)
new_image.close()
image.close()
print(image_data.shape, image_data.dtype)
```

I used the following command from the command line to execute the script:
```
python -Wall::ResourceWarning rw_bug.py 
```
(This is a cut-down example; I originally noticed this because we were getting lots of `ResourceWarning`s in our pillow-using test suite for a larger application.)

### What did you expect to happen?

I expected to see the following output on the command line, as a result of executing the script.
```
(512, 512) uint8
```

### What actually happened?

I got the following output on the command line:
```
/Users/mdickinson/.edm/envs/res3/lib/python3.6/site-packages/PIL/Image.py:844: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/mdickinson/Desktop/myimage.bmp'>
  self.load()
(512, 512) uint8
```

The problem doesn't seem to be specific to the BMP format; I also see this with TIFF image files.

### What versions of Pillow and Python are you using?

Pillow 4.0.0, Python 3.6.0.

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow. 

```python
import os

from PIL import Image
import numpy as np

image_path = os.path.expanduser("~/Desktop/myimage.bmp")
image = Image.open(image_path)
new_image = image.convert("L")  # ResourceWarning here!
image_data = np.array(new_image)
new_image.close()
image.close()
print(image_data.shape, image_data.dtype)
```

**Comment by wiredfool** [comment]
We're currently shipping Pillow 5.0, and open file handling was significantly reworked in 4.1.0.

**Comment by hugovk** [comment]
Confirmed reproducible in 4.0.0 and fixed in 4.1.0 and 5.0.0 (edited the script to also `print(Image.PILLOW_VERSION)`):

```
$ python --version
Python 3.6.4

$ pip install pillow==4.0.0
...
Successfully installed pillow-4.0.0

$ python -Wall::ResourceWarning /tmp/2991.py
4.0.0
/usr/local/lib/python3.6/site-packages/PIL/Image.py:844: ResourceWarning: unclosed file <_io.BufferedReader name='Tests/images/hopper.bmp'>
  self.load()
(128, 128) uint8

$ pip install pillow==4.1.0
...
Successfully installed pillow-4.1.0
$ python -Wall::ResourceWarning /tmp/2991.py
4.1.0
(128, 128) uint8

$ pip install -U pillow
Collecting pillow
...
Successfully installed pillow-5.0.0

$ python -Wall::ResourceWarning /tmp/2991.py
5.0.0
(128, 128) uint8
```

**Comment by mdickinson** [comment]
Great. Thanks for the quick response. I can confirm that I don't see the `ResourceWarning` from that example script with Pillow 5.0.0. I do unfortunately still see `ResourceWarning`s from our test suite, though. I'll investigate; I guess this issue should be closed in the mean time.

**Comment by mdickinson** [comment]
For the record, the `ResourceWarning` I was seeing with Pillow 4.0.0 was coming from [here](https://github.com/python-pillow/Pillow/blob/master/src/PIL/ImageFile.py#L257); and seemed to be the result of the local variable `read` being garbage collected at function-exit time (and so releasing the last reference to what was previously `self.fp`).

**Comment by mdickinson** [comment]
> I'll investigate

Done. It turns out that with 5.0.0, BMP images are okay, but not .tif images. New reproducer script looks like this:
```python
import os

from PIL import Image
import numpy as np

print("Pillow version: ", Image.PILLOW_VERSION)
image_path = os.path.expanduser("~/Desktop/myimage.tif")
image = Image.open(image_path)
new_image = image.convert("L")  # ResourceWarning here!
image_data = np.array(new_image)
new_image.close()
image.close()
print(image_data.shape, image_data.dtype)
```
Here's information about the image file:
```
(res3)bash-4.4$ file ~/Desktop/myimage.tif 
/Users/mdickinson/Desktop/myimage.tif: TIFF image data, little-endian, direntries=9, height=512, bps=8, compression=none, PhotometricIntepretation=BlackIsZero, width=512
```
And here's the output I get when I run the script:
```
(res3)bash-4.4$ python -Wall::ResourceWarning ~/Desktop/rw_bug.py 
Pillow version:  5.0.0
/Users/mdickinson/.edm/envs/res3/lib/python3.6/site-packages/PIL/TiffImagePlugin.py:1040: ResourceWarning: unclosed file <_io.TextIOWrapper name='/Users/mdickinson/Desktop/myimage.tif' mode='r' encoding='UTF-8'>
  return super(TiffImageFile, self).load()
(512, 512) uint8
```

**Comment by mdickinson** [comment]
It looks as though in the TIFF case it's [the mmap file pointer](https://github.com/python-pillow/Pillow/blob/5fd72be2071eb4e9176a2fe03ce9faba44693246/src/PIL/ImageFile.py#L177) that Python is now complaining about, rather than `self.fp` (which, as already pointed out, _is_ being closed properly in version 5.0.0). So this is a slightly different issue than the one I originally opened. Would you prefer me to close this issue and open a new one, or is it okay to repurpose this issue slightly?

**Comment by aclark4life** [comment]
@mdickinson Repurpose-away! Thanks

**Comment by aclark4life** [comment]
@mdickinson Maybe you opened a new issue … if not, feel free to reopen this one.

**Comment by radarhere** [comment]
The mmap file pointer issue was later raised by another user in #3184, and resolved in #3216
