### ISSUE TITLE
Metadata Warning, tag 34853 had too many entries

### ISSUE THREAD

**Issue by Ze-Yang** [python-pillow/Pillow#4896]
### What did you do?
Open an image and then use ImageOps.exif_transpose operation.

### What did you expect to happen?
No warning.

### What actually happened?
```
/home/zeyang/anaconda3/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:594: UserWarning: Metadata Warning, tag 34853 had too many entries: 10, expected 1
  % (tag, len(values))
```
### What are your OS, Python and Pillow versions?

* OS: ubuntu 16.04
* Python: 3.7.1
* Pillow: 7.2.0

```python
# codes to reproduce the warning
from PIL import Image, ImageOps
img = Image.open('d9af31bc74d18334.jpg')
img = ImageOps.exif_transpose(img)
```

[Image](https://user-images.githubusercontent.com/42920710/91961072-471b9780-ed3d-11ea-969b-cffc4af119b4.jpg) used for reproducing this error.

**Comment by radarhere** [comment]
Testing, I find this is resolved by #4862

**Comment by radarhere** [comment]
That PR has now been merged, so this fix will be a part of the next Pillow release, due on October 15.

**Comment by kunalbathija** [comment]
Hi, I am still facing same issue, I am on latest version 8.4.0

**Comment by radarhere** [comment]
@kunalbathija could you create a new issue with more detail? Self-contained example code?

**Comment by kunalbathija** [comment]
@radarhere I had used 163kb tif file and was getting this error then I used 71kb file and didn't get any error.

**Comment by radarhere** [comment]
This problem has moved to #5852
