### ISSUE TITLE
rounded_rectangle raises an "y1 should be > y0" even when coordinates are correctly ordered

### ISSUE THREAD

**Issue by ZRunner** [python-pillow/Pillow#7149]
### What did you do?

I recently updated one of my programs from 9.4 to 9.5 and got this new ValueError when drawing rounded rectangles on an image.

After some trials and error, I think the bug only happens when the rectangle height equals `1 + 2*radius`. I'm not 200% confident about that, but that's all I got so far.

The exact lines causing the error are https://github.com/python-pillow/Pillow/blob/2a274a476088c610451370b9b78e7c63b7b31da3/src/PIL/ImageDraw.py#L378-L383

### What did you expect to happen?

Well, PIL should be able to correctly calculate positions and draw my rounded corners.

### What actually happened?

```
Traceback (most recent call last):
  File "/.../test.py", line 17, in <module>
    main()
  File "/.../test.py", line 14, in main
    draw.rounded_rectangle(coordinates, radius=3, fill=(0, 0, 0))
  File "/.../env/lib/python3.9/site-packages/PIL/ImageDraw.py", line 385, in rounded_rectangle
    self.draw.draw_rectangle(left, fill, 1)
ValueError: y1 must be greater than or equal to y0
```

### What are your OS, Python and Pillow versions?

* OS: macOS 13.3.1
* Python: 3.9.16
* Pillow: 9.5.0

```python
from PIL import Image, ImageDraw

def main():
    # get a 1021x340 image
    img = Image.new('RGB', (20, 20), color=(255, 255, 255))
    # draw a rounded rectangle on it
    draw = ImageDraw.Draw(img)
    coordinates = (
        (5, 0),
        (15, 7)
    )
    # here's the bug:
    # on ImageDraw.py line 383, y1 from "left" will be 1px less than y0
    draw.rounded_rectangle(coordinates, radius=3, fill=(0, 0, 0))

if __name__ == '__main__':
    main()

```

**Comment by radarhere** [comment]
I've created PR #7151 to resolve this.

**Comment by sandydunlop** [comment]
I'm getting the same error from Pillow after updating the Minecraft Overviewer app to 0.19.10...

  File "/usr/local/lib/python3.11/site-packages/Minecraft_Overviewer-0.19.10-py3.11-macosx-13-x86_64.egg/overviewer_core/textures.py", line 4072, in repeater
    ImageDraw.Draw(torch).rectangle((0,24,10,15),outline=(0,0,0,0),fill=(0,0,0,0))
  File "/usr/local/lib/python3.11/site-packages/PIL/ImageDraw.py", line 294, in rectangle
    self.draw.draw_rectangle(xy, fill, 1)
ValueError: y1 must be greater than or equal to y0

**Comment by radarhere** [comment]
The first line you mention is https://github.com/overviewer/Minecraft-Overviewer/blob/13c1bddaf65dfaaf6c4c7a396c94db75bed4c089/overviewer_core/textures.py#L4072, so I would suggest raising an issue with https://github.com/overviewer/Minecraft-Overviewer

**Comment by Shaobo-Zhao** [comment]
dear ZRunner,did you solved this problem?

**Comment by radarhere** [comment]
@Shaobo-Zhao the problem should have been solved by #7151 in Pillow 10.0.0. If you upgrade to that version or later, it should be fixed.

**Comment by leleogere** [comment]
It seems that there is still an error here in version 10.2.0
```python
from PIL import Image, ImageDraw, __version__

print(__version__)

img = Image.new("RGBA", (1000, 10000), (0, 0, 0, 0))
draw = ImageDraw.Draw(img)

x, y, w, h = 294.5454545454545, 7103.020833333333, 32.727272727272805, 3.4895833333339397
draw.rounded_rectangle((x, y, x + w, y + h), radius=1)
```
Error:
```python
10.2.0
Traceback (most recent call last):
  File "/home/user/.config/JetBrains/PyCharm2023.3/scratches/scratch_1.py", line 7, in <module>
    draw.rounded_rectangle((x, y, x + w, y + h), fill=(255, 255, 255, 255), outline=(0, 0, 0, 255), radius=1)
  File "/home/user/anaconda3/envs/env/lib/python3.11/site-packages/PIL/ImageDraw.py", line 394, in rounded_rectangle
    self.draw.draw_rectangle(left, fill, 1)
ValueError: y1 must be greater than or equal to y0
```

**Comment by radarhere** [comment]
I've created https://github.com/python-pillow/Pillow/pull/7881 for this.

**Comment by air250** [comment]
I'm having this issue with  self.draw.draw_rectangle in the most current version was this resolved?
